---

- name: Create coder install directory
  file: path=/opt/coder owner=root group=root state=directory
  sudo: yes

- name: Install coder for the Drupal Codesniffer rules via composer
  command: composer global require drupal/coder:\>7 --working-dir=/opt/coder
  args:
    creates: /opt/coder/vendor/drupal/coder/coder.module
  sudo: yes

- name: Update bashrc to add drupalcs alias for Vagrant user
  lineinfile:
    dest=/home/vagrant/.bashrc
    line="alias drupalcs=phpcs --standard=/opt/coder/vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt"
    regexp="^alias drupalcs"
    owner=vagrant
    state=present
    insertafter=EOF
    create=True
