---
- name: Install unzip
  apt: name=unzip state=present install_recommends=no update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Copy Drupal archive
  unarchive:
    src={{ drupal_archive_path}}
    dest=/tmp/drupal-latest
  sudo: yes

- name: Rsync Drupal
  shell: rsync -ar --delete --exclude=sites/default/files/* /tmp/drupal-latest/docroot/ {{ drupal_docroot }}
  sudo: yes

- name: Set files permissions
  file: path={{ drupal_docroot }}/sites/default/files state=directory owner={{ apache_user | default('www-data') }} group={{ apache_user | default('www-data') }}
  sudo: yes

- name: Install Drupal
  shell: drush si --root={{ drupal_docroot }} --uri={{ drupal_uri }} --account-pass={{ drupal_admin_pass }} --y --db-url={{ drupal_db_url }} --db-su={{ drupal_db_su}} --db-su-pw={{ drupal_db_su_pw}} {{ drupal_install_profile }}

