---
- name: Install curl
  apt: name=curl state=present install_recommends=no update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /tmp
    creates: /usr/local/bin/composer
  sudo: no

- name: Move composer
  shell: mv /tmp/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  sudo: yes
