---

- name: Install MySQL
  apt: name=mysql-server state=present install_recommends=no update_cache=yes cache_valid_time=3600
  sudo: yes

# Ansible needs this to configure MySQL with
- name: Python MySQL driver
  apt: name=python-mysqldb state=present install_recommends=no
  sudo: yes

- name: Create MySQL config file
  action: template src=mysql.my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql
  sudo: yes

- name: Start MySQL
  service: name=mysql state=started
  sudo: yes

- name: Set MySQL root password
  mysql_user: name=root password={{ mysql_root_password }} host=localhost

- name: Remove MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password }}