---
- name: Install unzip
  apt: name=unzip state=present install_recommends=no update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Create temporary unzip location
  file: path=/tmp/drupal-latest state=directory

- name: Empty temporary unzip location
  shell: rm -rf /tmp/drupal-latest/*
  sudo: yes

- name: Copy Drupal archive
  unarchive:
    src={{ drupal_archive_path }}
    dest=/tmp/drupal-latest
  sudo: yes

- name: Rsync Drupal
  shell: rsync -ar --delete --exclude=sites/default/settings.php --exclude=sites/default/local_settings.php --exclude=sites/default/files/* /tmp/drupal-latest/docroot/ {{ drupal_docroot }}
  sudo: yes

- name: Set code permissions
  file: path={{ drupal_docroot }} state=directory owner={{ code_user | default('ubuntu') }} group={{ code_group | default('ubuntu') }} recurse=yes
  sudo: yes

- name: Install Drupal
  shell: drush si -y --root={{ drupal_docroot }} --uri={{ drupal_uri }} --account-pass={{ drupal_admin_pass }} --db-url=mysql://{{ drupal_db_user }}:{{ drupal_db_pass }}@{{ drupal_db_host }}/{{ drupal_db_name }} --db-su={{ drupal_db_su }} --db-su-pw={{ drupal_db_su_pw }} {{ drupal_install_profile }} {{ drupal_install_extras | default('') }}
  sudo: yes
  sudo_user: "{{ code_user | default('ubuntu') }}"
  when: drupal_install is defined and drupal_install

- name: Set up local settings
  template: src=local_settings.php.j2 dest={{ drupal_docroot }}/sites/default/local_settings.php
  sudo: yes

- name: Settings files permissions
  file:
    path={{ item }}
    mode=0644
  with_items:
    - "{{ drupal_docroot }}/sites/default/local_settings.php"
    - "{{ drupal_docroot }}/sites/default/settings.php"
  sudo: yes

- name: Include local settings
  lineinfile:
    dest={{ drupal_docroot }}/sites/default/settings.php
    line="include dirname(__FILE__) . '/local_settings.php';"
    state=present
  sudo: yes

- name: Run rebuild script
  shell: /tmp/drupal-latest/scripts/deployment/rebuild.sh
  sudo: yes
  when: drupal_update is defined and drupal_update
  environment:
    FORCE_DOWNLOAD: "1"
    ENVIRONMENT: "{{ drupal_environment }}"
    DRUPAL_DOCROOT: "{{ drupal_docroot }}"
    DRUPAL_DB_SU: "{{ drupal_db_su }}"
    DRUPAL_DB_SU_PW: "{{ drupal_db_su_pw }}"
    DRUPAL_DB_NAME: "{{ drupal_db_name }}"
    DRUPAL_DB_HOST: "{{ drupal_db_host }}"

- name: Run deploy script
  shell: /tmp/drupal-latest/scripts/deployment/deploy.sh
  sudo: yes
  when: drupal_deploy is defined and drupal_deploy
  environment:
    ENVIRONMENT: "{{ drupal_environment }}"
    DRUPAL_DOCROOT: "{{ drupal_docroot }}"

- name: Set files permissions
  file: 
    path={{ drupal_docroot }}/sites/default/files 
    state=directory owner={{ apache_user | default('www-data') }} 
    group={{ code_user | default('ubuntu') }}
    recurse=yes
  sudo: yes

- name: Revert features
  shell: drush fra -y --root={{ drupal_docroot }} --uri={{ drupal_uri }}
  when: drupal_install is defined and drupal_install

- name: Clear cache
  shell: drush cc all --root={{ drupal_docroot }} --uri={{ drupal_uri }}
